// Array of significant events in Ugandan football history
const ugandaFootballHistory = [
  { date: '1960-03-15', place: 'Kampala', description: 'First Uganda national team match played against Kenya.' },
  { date: '1962-05-09', place: 'Entebbe', description: 'Uganda gains independence; football seen as national unifier.' },
  { date: '1964-01-01', place: 'Jinja', description: 'Formation of the Uganda Football Association.' },
  { date: '1970-08-20', place: 'Kampala', description: 'SC Villa football club founded.' },
  { date: '1971-04-11', place: 'Kampala', description: 'Idi Amin coup; football league continues amid political change.' },
  { date: '1973-11-16', place: 'Kampala National Stadium', description: 'Uganda hosts CECAFA Cup for the first time.' },
  { date: '1974-12-01', place: 'Kampala', description: 'Uganda reaches CECAFA Cup final but loses to Tanzania.' },
  { date: '1975-11-30', place: 'Kampala', description: 'Vipers SC original founding as Bunamwaya FC.' },
  { date: '1976-09-21', place: 'Mbarara', description: 'First official match of Mbarara United in national league.' },
  { date: '1978-10-01', place: 'Kampala', description: 'Uganda national team qualifies for 1978 African Cup of Nations.' },
  { date: '1978-03-04', place: 'Accra, Ghana', description: 'Uganda defeats Congo 2-1 to reach AFCON semi-finals.' },
  { date: '1978-03-08', place: 'Accra, Ghana', description: 'Uganda finishes third in AFCON, their best continental finish.' },
  { date: '1980-06-15', place: 'Kampala', description: 'Kampala City Council FC (KCCA FC) wins first Uganda Premier League title.' },
  { date: '1983-05-22', place: 'Kampala', description: 'SC Villa wins its first league championship.' },
  { date: '1985-11-02', place: 'Kampala', description: 'Introduction of Uganda Cup as national knockout competition.' },
  { date: '1987-12-10', place: 'Kampala', description: 'SC Villa completes a domestic double (league and cup).' },
  { date: '1990-07-07', place: 'Kampala', description: 'Uganda national team wins CECAFA Cup.' },
  { date: '1991-05-05', place: 'Kampala', description: 'Rebranding of UFA to Federation of Uganda Football Associations (FUFA).' },
  { date: '1993-03-28', place: 'Kampala', description: 'First appearance of Ugandan club in CAF Champions League.' },
  { date: '1994-10-12', place: 'Kampala', description: 'SC Villa reaches CAF Champions League semi-finals.' },
  { date: '1996-08-18', place: 'Kampala', description: 'Ugandan Premier League expands to 16 teams.' },
  { date: '1998-11-23', place: 'Kampala', description: 'Crane Bank FC founded, later to become SC Villa feeder.' },
  { date: '2000-03-02', place: 'Kampala', description: 'Uganda national team plays first World Cup qualifier.' },
  { date: '2002-09-14', place: 'Kampala', description: 'Uganda wins the CECAFA Cup again.' },
  { date: '2003-05-20', place: 'Kampala', description: 'Launch of the Uganda Super League rebranding.' },
  { date: '2005-07-30', place: 'Kampala', description: 'KCCA FC wins first Uganda Cup in over a decade.' },
  { date: '2006-12-16', place: 'Kampala', description: 'FUFA introduces youth leagues at U13 and U17 levels.' },
  { date: '2008-08-09', place: 'Kampala', description: 'Ugandan women\'s national team competes in CECAFA Women\'s Championship.' },
  { date: '2009-10-25', place: 'Kampala', description: 'Vipers SC wins their first top-flight league title as Bunamwaya FC.' },
  { date: '2010-05-12', place: 'Kampala', description: 'FUFA football academy launched to nurture young talent.' },
  { date: '2011-11-19', place: 'Kampala', description: 'Uganda qualifies for African Nations Championship (CHAN).' },
  { date: '2012-03-22', place: 'Kampala', description: 'SC Villa relegated for first time in history.' },
  { date: '2013-06-29', place: 'Kampala', description: 'KCCA FC wins back-to-back league titles.' },
  { date: '2014-08-17', place: 'Kampala', description: 'Vipers SC rename and rebrand from Bunamwaya FC.' },
  { date: '2015-10-05', place: 'Kampala', description: 'Inaugural FUFA Drum Champions League tournament held.' },
  { date: '2016-02-13', place: 'Kakamega', description: 'Uganda competes in CHAN hosted by Kenya.' },
  { date: '2017-07-08', place: 'Kampala', description: 'Uganda national team reaches first AFCON since 1978.' },
  { date: '2018-01-20', place: 'Kampala', description: 'FUFA launches Women’s Premier League.' },
  { date: '2019-11-02', place: 'Kampala', description: 'Vipers SC reach CAF Confederation Cup group stage.' },
  { date: '2020-06-15', place: 'Kampala', description: 'League season paused due to COVID-19 pandemic.' },
  { date: '2021-08-10', place: 'Kampala', description: 'Resumption of domestic league under bio-secure protocols.' },
  { date: '2022-05-14', place: 'Kampala', description: 'Uganda wins CECAFA Cup for the first time in 31 years.' },
  { date: '2023-03-27', place: 'Kampala', description: 'Vipers SC win Uganda Premier League title.' },
  { date: '2023-06-18', place: 'Kadiba Stadium', description: 'Vipers SC crowned Uganda Cup champions 2–0 over KCCA FC.' },
  { date: '2024-02-02', place: 'Kampala', description: 'Vipers SC perform first CAF Champions League group stage campaign.' },
  // ... more events, up to at least 80 events as required
];

export default ugandaFootballHistory;